/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface C3Card {
        /**
          * Which side of the card the image should render on
         */
        "cardOrientation": string;
        /**
          * The theme of the card, dictacting look / feel
         */
        "cardStyle": string;
        /**
          * CSS classes to be optionally appended to the wrapper
         */
        "classes": string;
        /**
          * Should the card be full bleed?
         */
        "fullBleed": boolean;
        /**
          * Determines if the header is inline
         */
        "headerInline": boolean;
        /**
          * Determines if the header is a link
         */
        "headerLink": boolean;
    }
    interface C3ImageGrid {
        /**
          * The number of columns to render
         */
        "numColumns": string;
    }
    interface C3Modal {
    }
    interface C3OffCanvas {
    }
    interface StaticRouter {
        /**
          * Contains the active page's markup from the node server
         */
        "markup": any;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLC3CardElement extends Components.C3Card, HTMLStencilElement {
    }
    var HTMLC3CardElement: {
        prototype: HTMLC3CardElement;
        new (): HTMLC3CardElement;
    };
    interface HTMLC3ImageGridElement extends Components.C3ImageGrid, HTMLStencilElement {
    }
    var HTMLC3ImageGridElement: {
        prototype: HTMLC3ImageGridElement;
        new (): HTMLC3ImageGridElement;
    };
    interface HTMLC3ModalElement extends Components.C3Modal, HTMLStencilElement {
    }
    var HTMLC3ModalElement: {
        prototype: HTMLC3ModalElement;
        new (): HTMLC3ModalElement;
    };
    interface HTMLC3OffCanvasElement extends Components.C3OffCanvas, HTMLStencilElement {
    }
    var HTMLC3OffCanvasElement: {
        prototype: HTMLC3OffCanvasElement;
        new (): HTMLC3OffCanvasElement;
    };
    interface HTMLStaticRouterElement extends Components.StaticRouter, HTMLStencilElement {
    }
    var HTMLStaticRouterElement: {
        prototype: HTMLStaticRouterElement;
        new (): HTMLStaticRouterElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "c3-card": HTMLC3CardElement;
        "c3-image-grid": HTMLC3ImageGridElement;
        "c3-modal": HTMLC3ModalElement;
        "c3-off-canvas": HTMLC3OffCanvasElement;
        "static-router": HTMLStaticRouterElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface C3Card {
        /**
          * Which side of the card the image should render on
         */
        "cardOrientation"?: string;
        /**
          * The theme of the card, dictacting look / feel
         */
        "cardStyle"?: string;
        /**
          * CSS classes to be optionally appended to the wrapper
         */
        "classes"?: string;
        /**
          * Should the card be full bleed?
         */
        "fullBleed"?: boolean;
        /**
          * Determines if the header is inline
         */
        "headerInline"?: boolean;
        /**
          * Determines if the header is a link
         */
        "headerLink"?: boolean;
    }
    interface C3ImageGrid {
        /**
          * The number of columns to render
         */
        "numColumns"?: string;
    }
    interface C3Modal {
    }
    interface C3OffCanvas {
        /**
          * Toggles visibilty of the panel
         */
        "onToggleLeftPanel"?: (event: CustomEvent<any>) => void;
    }
    interface StaticRouter {
        /**
          * Contains the active page's markup from the node server
         */
        "markup"?: any;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "c3-card": C3Card;
        "c3-image-grid": C3ImageGrid;
        "c3-modal": C3Modal;
        "c3-off-canvas": C3OffCanvas;
        "static-router": StaticRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "c3-card": LocalJSX.C3Card & JSXBase.HTMLAttributes<HTMLC3CardElement>;
            "c3-image-grid": LocalJSX.C3ImageGrid & JSXBase.HTMLAttributes<HTMLC3ImageGridElement>;
            "c3-modal": LocalJSX.C3Modal & JSXBase.HTMLAttributes<HTMLC3ModalElement>;
            "c3-off-canvas": LocalJSX.C3OffCanvas & JSXBase.HTMLAttributes<HTMLC3OffCanvasElement>;
            "static-router": LocalJSX.StaticRouter & JSXBase.HTMLAttributes<HTMLStaticRouterElement>;
        }
    }
}
