import { ExternalLink, Star, GitFork } from "lucide-react"

const PROJECTS = [
  {
    name: "jizo",
    desc: "Tool to help view reports generated by Deque's Axe CLI accessibility tool.",
    lang: "TypeScript",
    stars: 3,
    forks: 0,
    url: "https://github.com/ctangney-tulip/jizo",
  },
  {
    name: "node-matrix-grid",
    desc: "HTML5 canvas grid that listens to click events — a basic example of tying a NodeMatrix data structure to something like a game board.",
    lang: "JavaScript",
    stars: 0,
    forks: 0,
    url: "https://github.com/cjtangney/node-matrix-grid",
  },
  {
    name: "cjtangney",
    desc: "My personal website — the one this desktop is modeled after.",
    lang: "TypeScript",
    stars: 0,
    forks: 0,
    url: "https://github.com/cjtangney/cjtangney",
  },
]

const LANG_COLOR: Record<string, string> = {
  TypeScript: "oklch(0.65 0.15 200)",
  JavaScript: "oklch(0.8 0.16 90)",
  Rust: "oklch(0.7 0.17 35)",
  Shell: "oklch(0.7 0.16 140)",
}

export function ProjectsApp() {
  return (
    <div className="grid gap-3 p-5 sm:grid-cols-2">
      {PROJECTS.map((p) => (
        <a
          key={p.name}
          href={p.url}
          target="_blank"
          rel="noreferrer"
          className="group flex flex-col gap-3 rounded-xl border border-border bg-secondary/30 p-4 transition-colors hover:border-primary/50 hover:bg-secondary/60"
        >
          <div className="flex items-center justify-between">
            <h3 className="font-mono text-sm font-medium text-foreground">
              ~/{p.name}
            </h3>
            <ExternalLink className="size-4 text-muted-foreground transition-colors group-hover:text-primary" />
          </div>
          <p className="text-sm leading-relaxed text-muted-foreground">
            {p.desc}
          </p>
          <div className="mt-auto flex items-center gap-4 font-mono text-xs text-muted-foreground">
            <span className="flex items-center gap-1.5">
              <span
                className="size-2.5 rounded-full"
                style={{ backgroundColor: LANG_COLOR[p.lang] }}
              />
              {p.lang}
            </span>
            <span className="flex items-center gap-1">
              <Star className="size-3.5" /> {p.stars}
            </span>
            <span className="flex items-center gap-1">
              <GitFork className="size-3.5" /> {p.forks}
            </span>
          </div>
        </a>
      ))}
    </div>
  )
}
